### ISSUE TITLE
panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by inotnako** [gophergala/gopherling#2]
```
panic: concurrent write to websocket connection
goroutine 123 [running]:
panic(0x33fa00, 0xc8206329f0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/gorilla/websocket.(*Conn).flushFrame(0xc8202ad700, 0x778c01, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/antonkonovalov/go/src/github.com/gorilla/websocket/conn.go:450 +0x5ba
github.com/gorilla/websocket.(*Conn).NextWriter(0xc8202ad700, 0x1, 0x0, 0x0, 0x0, 0x0)
    /Users/antonkonovalov/go/src/github.com/gorilla/websocket/conn.go:378 +0x9b
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc8202ad700, 0x3f37a0, 0xc820567660, 0x0, 0x0)
    /Users/antonkonovalov/go/src/github.com/gorilla/websocket/json.go:22 +0x4b
github.com/gophergala/gopherling/loader.(*loader).spawnClient(0xc8202ea4b0, 0xc8202e8fb0, 0xc82005ce40)
    /Users/antonkonovalov/go/src/github.com/gophergala/gopherling/loader/loader.go:83 +0x47f
github.com/gophergala/gopherling/loader.(*loader).Run.func1(0xc8202ea4b0, 0xc8202e8fb0, 0xc82005ce40)
    /Users/antonkonovalov/go/src/github.com/gophergala/gopherling/loader/loader.go:106 +0x35
created by github.com/gophergala/gopherling/loader.(*loader).Run
    /Users/antonkonovalov/go/src/github.com/gophergala/gopherling/loader/loader.go:107 +0xb4
```

**Comment by mikesaidani** [comment]
Thank you, i'll look into it.

**Comment by edwindvinas** [comment]
Hi! I also encounter the issue. May I know how to fix this?
